// This file is automatically generated
// If you are manually updating this version, please
// also update the onnx one at
// src/main/groovy/ossci/onnx/DockerVersion.groovy
// to the same version
package ossci.caffe2
class DockerVersion {
  static final String version = "115";
}
