// This file is automatically generated
// <DockerVersion>190</DockerVersion>  # This line is needed by CircleCI builds, please don't remove it
package ossci.caffe2
class DockerVersion {
  static final String version = "194";
}
