// This file is automatically generated
// If you are manually updating this version, please
// also update the tensorcomp one at
// src/main/groovy/ossci/tensorcomp/DockerVersion.groovy
// to the same version
package ossci.tensorcomp
class DockerVersion {
  static final String version = "16";
}
