// This file is automatically generated
// <DockerVersion>242</DockerVersion>  # This line is needed by CircleCI builds, please don't remove it
package ossci.pytorch
class DockerVersion {
  static final String version = "242";
}
