// This file is automatically generated
// <DockerVersion>238</DockerVersion>  # This line is needed by CircleCI builds, please don't remove it
package ossci.pytorch
class DockerVersion {
  static final String version = "239";
}
